# Generated by Django 4.1.3 on 2022-12-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='comentario',
            field=models.TextField(default=True, max_length=200),
        ),
    ]
