# Generated by Django 4.1.3 on 2022-12-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='comentario',
            field=models.TextField(default=False, max_length=200),
        ),
    ]
