# Generated by Django 4.1.3 on 2022-12-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_noticia_segundo_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='Email',
            field=models.EmailField(default=' ', max_length=254),
        ),
    ]
